#!/bin/bash
echo "This script creates a new converter vec${1}Converter for a given type ${2}"
if [ "$#" -ne 1 ]; then
    echo "Usage: $ ${0} <c-type in project name> <c-type in source code>"
    exit
fi
# Start it like: makeVecConverter Double double
cp -r vecFloatConverter vec${1}Converter
cat vecFloatConverter/main.hpp | sed "s#float#${2}#g" | sed "s#Float#${1}#g" > vec${1}Converter/main.hpp
