# Check the build type and set it to "release" if nothing is set
STRING(TOLOWER "${CMAKE_BUILD_TYPE}" CMAKE_BUILD_TYPE)
IF (CMAKE_BUILD_TYPE MATCHES "debug")
    message("DEBUG MODE")
    add_definitions(-DINFO_MSG_)
    add_definitions(-DDEBUG_MSG_)
    add_definitions(-DSUCCESS_MSG_)
    add_definitions(-DWARNING_MSG_)
    add_definitions(-DERROR_MSG_)
ELSEIF (CMAKE_BUILD_TYPE MATCHES "ship")
    message("SHIP MODE: ALL OUTPUTS WILL BE DISABLED")
    SET (CMAKE_BUILD_TYPE "release")
ELSE ()
    message("RELEASE MODE: DISABLE DEBUG MESSAGES")
    add_definitions(-DINFO_MSG_)
    add_definitions(-DSUCCESS_MSG_)
    add_definitions(-DWARNING_MSG_)
    add_definitions(-DERROR_MSG_)
    SET (CMAKE_BUILD_TYPE "release")
ENDIF ()
message("Build Type: ${CMAKE_BUILD_TYPE}")

